site_name: "CNMP-Doc"

repo_name: "CNMP-Doc"
repo_url: "https://github.com/CNMP-Coleta-Indicadores/CNMP-Doc"

theme:
  name: "material"

  logo: "assets/CNMP.jpg"
  favicon: "assets/CNMP.jpg"
  palette:
    primary: "#fff"
    accent: "#0B4D9B"


extra_css:
  - stylesheets/styles.css

nav:
  - Home: index.md



plugins:
  - search
